### ISSUE TITLE
Abdullajon, a tagi hrefida ./ qo'ysang yaxshi bo'ladi 

### ISSUE THREAD

**Issue by Nurmuhammad-Ikromov** [Abdullo001/Coffee-Roaster#1]
![Снимок экрана (397)](https://user-images.githubusercontent.com/104080312/170276557-65574113-4ab5-4043-9cfa-a20f874b7a57.png)

**Comment by Abdullo001** [comment]
ishing bolmasin bu mani ishim😡😡😡😡

**Comment by Nurmuhammad-Ikromov** [comment]
> ishing bolmasin bu mani ishim😡😡😡😡

ture chumo😂
